// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scrapers.Persistence;

#nullable disable

namespace Scrapers.Persistence.Migrations
{
    [DbContext(typeof(ClinicalTrialsContext))]
    [Migration("20260708215528_AddIsNonEnglishToPubmedStudies")]
    partial class AddIsNonEnglishToPubmedStudies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Affiliation")
                        .HasColumnType("text")
                        .HasColumnName("affiliation");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyNctId");

                    b.ToTable("investigators", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PubmedStudyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorsJson")
                        .HasColumnType("text")
                        .HasColumnName("authors_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Doi")
                        .HasColumnType("text")
                        .HasColumnName("doi");

                    b.Property<bool>("IsNonEnglish")
                        .HasColumnType("boolean")
                        .HasColumnName("is_non_english");

                    b.Property<string>("Journal")
                        .HasColumnType("text")
                        .HasColumnName("journal");

                    b.Property<string>("Pmid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pmid");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publication_date");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("StudyNctId", "Pmid")
                        .IsUnique();

                    b.ToTable("pubmed_studies", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyEntity", b =>
                {
                    b.Property<string>("NctId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nct_id");

                    b.Property<string>("BriefTitle")
                        .HasColumnType("text")
                        .HasColumnName("brief_title");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsIncomplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_incomplete");

                    b.Property<string>("OverallStatus")
                        .HasColumnType("text")
                        .HasColumnName("overall_status");

                    b.HasKey("NctId");

                    b.ToTable("studies", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Investigators")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PubmedStudyEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("PubmedStudies")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyEntity", b =>
                {
                    b.Navigation("Investigators");

                    b.Navigation("PubmedStudies");
                });
#pragma warning restore 612, 618
        }
    }
}
