// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scrapers.Persistence;

#nullable disable

namespace Scrapers.Persistence.Migrations
{
    [DbContext(typeof(ClinicalTrialsContext))]
    [Migration("20260708191631_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Affiliation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSuccessfulPubmedCrawl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NcbiId")
                        .HasColumnType("text");

                    b.Property<string>("OrcidId")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<int>("StudyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.ToTable("investigators", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PubmedStudyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("InvestigatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Keywords")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvestigatorId");

                    b.ToTable("pubmed_studies", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BriefTitle")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("NctId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OverallStatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NctId")
                        .IsUnique();

                    b.ToTable("studies", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Investigators")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PubmedStudyEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.InvestigatorEntity", "Investigator")
                        .WithMany("PubmedStudies")
                        .HasForeignKey("InvestigatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investigator");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorEntity", b =>
                {
                    b.Navigation("PubmedStudies");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyEntity", b =>
                {
                    b.Navigation("Investigators");
                });
#pragma warning restore 612, 618
        }
    }
}
