// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scrapers.Persistence;

#nullable disable

namespace Scrapers.Persistence.Migrations
{
    [DbContext(typeof(ClinicalTrialsContext))]
    partial class ClinicalTrialsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Scrapers.Persistence.Entities.CategoryAggregationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_name");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_type");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<int>("PubmedPaperCount")
                        .HasColumnType("integer")
                        .HasColumnName("pubmed_paper_count");

                    b.Property<int>("StudyCount")
                        .HasColumnType("integer")
                        .HasColumnName("study_count");

                    b.Property<string>("StudyNctIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("study_nct_ids");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName");

                    b.HasIndex("CategoryType");

                    b.ToTable("category_aggregations", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.DataSourceStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("LastSyncHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_sync_hash");

                    b.Property<DateTime?>("LastSyncTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_timestamp");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SourceName")
                        .IsUnique();

                    b.ToTable("data_source_state", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorAffiliationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("country");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("institution_name");

                    b.Property<Guid>("InvestigatorPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("investigator_person_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("State")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionName");

                    b.HasIndex("InvestigatorPersonId");

                    b.ToTable("investigator_affiliations", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Affiliation")
                        .HasColumnType("text")
                        .HasColumnName("affiliation");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyNctId");

                    b.ToTable("investigators", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorPersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("full_name");

                    b.Property<string>("NcbiId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ncbi_id");

                    b.Property<string>("Orcid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("orcid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verification_source");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("NcbiId")
                        .IsUnique()
                        .HasFilter("ncbi_id IS NOT NULL");

                    b.HasIndex("Orcid")
                        .IsUnique()
                        .HasFilter("orcid IS NOT NULL");

                    b.ToTable("investigator_persons", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PiAggregationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Affiliation")
                        .HasColumnType("text")
                        .HasColumnName("affiliation");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<string>("InvestigatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("investigator_name");

                    b.Property<int>("PubmedPaperCount")
                        .HasColumnType("integer")
                        .HasColumnName("pubmed_paper_count");

                    b.Property<int>("StudyCount")
                        .HasColumnType("integer")
                        .HasColumnName("study_count");

                    b.Property<string>("StudyNctIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("study_nct_ids");

                    b.HasKey("Id");

                    b.HasIndex("InvestigatorName");

                    b.ToTable("pi_aggregations", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PipelineEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimed_by");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_error_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventType");

                    b.HasIndex("Status");

                    b.ToTable("pipeline_events", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PipelineRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TotalAuthors")
                        .HasColumnType("integer")
                        .HasColumnName("total_authors");

                    b.Property<int?>("TotalInvestigators")
                        .HasColumnType("integer")
                        .HasColumnName("total_investigators");

                    b.Property<int?>("TotalKeywords")
                        .HasColumnType("integer")
                        .HasColumnName("total_keywords");

                    b.Property<int?>("TotalPubmedPapers")
                        .HasColumnType("integer")
                        .HasColumnName("total_pubmed_papers");

                    b.Property<int?>("TotalStudies")
                        .HasColumnType("integer")
                        .HasColumnName("total_studies");

                    b.HasKey("Id");

                    b.ToTable("pipeline_runs", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PubmedStudyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abstract")
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Doi")
                        .HasColumnType("text")
                        .HasColumnName("doi");

                    b.Property<bool>("IsNonEnglish")
                        .HasColumnType("boolean")
                        .HasColumnName("is_non_english");

                    b.Property<string>("Journal")
                        .HasColumnType("text")
                        .HasColumnName("journal");

                    b.Property<string>("Pmid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pmid");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publication_date");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("StudyNctId", "Pmid")
                        .IsUnique();

                    b.ToTable("pubmed_studies", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.ScrapeEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("PipelineRunId")
                        .HasColumnType("integer")
                        .HasColumnName("pipeline_run_id");

                    b.Property<int?>("RecordsAffected")
                        .HasColumnType("integer")
                        .HasColumnName("records_affected");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("PipelineRunId");

                    b.HasIndex("Source");

                    b.HasIndex("Timestamp");

                    b.ToTable("scrape_events", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.ScraperPivotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer")
                        .HasColumnName("batch_size");

                    b.Property<int>("CacheTtlDays")
                        .HasColumnType("integer")
                        .HasColumnName("cache_ttl_days");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("scraper_pivots", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.SourceFetchHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastFetchTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fetch_timestamp");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_type");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StudyNctId");

                    b.HasIndex("StudyNctId", "SourceType")
                        .IsUnique();

                    b.ToTable("source_fetch_history", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyAuthorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ForeName")
                        .HasColumnType("text")
                        .HasColumnName("fore_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Orcid")
                        .HasColumnType("text")
                        .HasColumnName("orcid");

                    b.Property<string>("Pmid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pmid");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.HasKey("Id");

                    b.HasIndex("LastName");

                    b.HasIndex("Orcid");

                    b.HasIndex("StudyNctId");

                    b.ToTable("study_authors", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyConditionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.HasKey("Id");

                    b.HasIndex("Condition");

                    b.HasIndex("StudyNctId");

                    b.ToTable("study_conditions", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyEntity", b =>
                {
                    b.Property<string>("NctId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nct_id");

                    b.Property<string>("Allocation")
                        .HasColumnType("text")
                        .HasColumnName("allocation");

                    b.Property<string>("BriefSummary")
                        .HasColumnType("text")
                        .HasColumnName("brief_summary");

                    b.Property<string>("BriefTitle")
                        .HasColumnType("text")
                        .HasColumnName("brief_title");

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("completion_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EnrollmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_count");

                    b.Property<string>("InterventionModel")
                        .HasColumnType("text")
                        .HasColumnName("intervention_model");

                    b.Property<bool>("IsIncomplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_incomplete");

                    b.Property<string>("MaximumAge")
                        .HasColumnType("text")
                        .HasColumnName("maximum_age");

                    b.Property<string>("MinimumAge")
                        .HasColumnType("text")
                        .HasColumnName("minimum_age");

                    b.Property<string>("OfficialTitle")
                        .HasColumnType("text")
                        .HasColumnName("official_title");

                    b.Property<string>("OverallStatus")
                        .HasColumnType("text")
                        .HasColumnName("overall_status");

                    b.Property<string>("PrimaryPurpose")
                        .HasColumnType("text")
                        .HasColumnName("primary_purpose");

                    b.Property<string>("Sex")
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateOnly?>("StudyFirstPostDate")
                        .HasColumnType("date")
                        .HasColumnName("study_first_post_date");

                    b.Property<string>("StudyType")
                        .HasColumnType("text")
                        .HasColumnName("study_type");

                    b.HasKey("NctId");

                    b.ToTable("studies", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyInvestigatorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_phone");

                    b.Property<Guid>("InvestigatorPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("investigator_person_id");

                    b.Property<bool>("IsOverallOfficial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_overall_official");

                    b.Property<string>("RoleOnStudy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role_on_study");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.HasKey("Id");

                    b.HasIndex("InvestigatorPersonId");

                    b.HasIndex("StudyNctId", "InvestigatorPersonId");

                    b.ToTable("study_investigators", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyKeywordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.HasKey("Id");

                    b.HasIndex("Keyword");

                    b.HasIndex("StudyNctId");

                    b.ToTable("study_keywords", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyLocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Facility")
                        .HasColumnType("text")
                        .HasColumnName("facility");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("Country");

                    b.HasIndex("Facility");

                    b.HasIndex("State");

                    b.HasIndex("StudyNctId");

                    b.ToTable("study_locations", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyPhaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyNctId");

                    b.ToTable("study_phases", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyReferenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Citation")
                        .HasColumnType("text")
                        .HasColumnName("citation");

                    b.Property<string>("Pmid")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pmid");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Pmid");

                    b.HasIndex("StudyNctId");

                    b.ToTable("study_references", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorAffiliationEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.InvestigatorPersonEntity", "InvestigatorPerson")
                        .WithMany("Affiliations")
                        .HasForeignKey("InvestigatorPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestigatorPerson");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Investigators")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PubmedStudyEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("PubmedStudies")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.ScrapeEventEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.PipelineRunEntity", "PipelineRun")
                        .WithMany()
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PipelineRun");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyAuthorEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Authors")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyConditionEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Conditions")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyInvestigatorEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.InvestigatorPersonEntity", "InvestigatorPerson")
                        .WithMany("StudyInvestigators")
                        .HasForeignKey("InvestigatorPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("StudyInvestigators")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestigatorPerson");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyKeywordEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Keywords")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyLocationEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Locations")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyPhaseEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Phases")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyReferenceEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("References")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorPersonEntity", b =>
                {
                    b.Navigation("Affiliations");

                    b.Navigation("StudyInvestigators");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyEntity", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Conditions");

                    b.Navigation("Investigators");

                    b.Navigation("Keywords");

                    b.Navigation("Locations");

                    b.Navigation("Phases");

                    b.Navigation("PubmedStudies");

                    b.Navigation("References");

                    b.Navigation("StudyInvestigators");
                });
#pragma warning restore 612, 618
        }
    }
}
