// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scrapers.Persistence;

#nullable disable

namespace Scrapers.Persistence.Migrations
{
    [DbContext(typeof(ClinicalTrialsContext))]
    partial class ClinicalTrialsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.3.25171.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Scrapers.Persistence.Entities.CategoryAggregationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_name");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_type");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<int>("PubmedPaperCount")
                        .HasColumnType("integer")
                        .HasColumnName("pubmed_paper_count");

                    b.Property<int>("StudyCount")
                        .HasColumnType("integer")
                        .HasColumnName("study_count");

                    b.Property<string>("StudyNctIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("study_nct_ids");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName");

                    b.HasIndex("CategoryType");

                    b.ToTable("category_aggregations", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Affiliation")
                        .HasColumnType("text")
                        .HasColumnName("affiliation");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyNctId");

                    b.ToTable("investigators", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PiAggregationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Affiliation")
                        .HasColumnType("text")
                        .HasColumnName("affiliation");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<string>("InvestigatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("investigator_name");

                    b.Property<int>("PubmedPaperCount")
                        .HasColumnType("integer")
                        .HasColumnName("pubmed_paper_count");

                    b.Property<int>("StudyCount")
                        .HasColumnType("integer")
                        .HasColumnName("study_count");

                    b.Property<string>("StudyNctIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("study_nct_ids");

                    b.HasKey("Id");

                    b.HasIndex("InvestigatorName");

                    b.ToTable("pi_aggregations", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PipelineRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TotalAuthors")
                        .HasColumnType("integer")
                        .HasColumnName("total_authors");

                    b.Property<int?>("TotalInvestigators")
                        .HasColumnType("integer")
                        .HasColumnName("total_investigators");

                    b.Property<int?>("TotalKeywords")
                        .HasColumnType("integer")
                        .HasColumnName("total_keywords");

                    b.Property<int?>("TotalPubmedPapers")
                        .HasColumnType("integer")
                        .HasColumnName("total_pubmed_papers");

                    b.Property<int?>("TotalStudies")
                        .HasColumnType("integer")
                        .HasColumnName("total_studies");

                    b.HasKey("Id");

                    b.ToTable("pipeline_runs", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PubmedStudyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abstract")
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Doi")
                        .HasColumnType("text")
                        .HasColumnName("doi");

                    b.Property<bool>("IsNonEnglish")
                        .HasColumnType("boolean")
                        .HasColumnName("is_non_english");

                    b.Property<string>("Journal")
                        .HasColumnType("text")
                        .HasColumnName("journal");

                    b.Property<string>("Pmid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pmid");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publication_date");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("StudyNctId", "Pmid")
                        .IsUnique();

                    b.ToTable("pubmed_studies", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.ScrapeEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("PipelineRunId")
                        .HasColumnType("integer")
                        .HasColumnName("pipeline_run_id");

                    b.Property<int?>("RecordsAffected")
                        .HasColumnType("integer")
                        .HasColumnName("records_affected");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("PipelineRunId");

                    b.HasIndex("Source");

                    b.HasIndex("Timestamp");

                    b.ToTable("scrape_events", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyAuthorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ForeName")
                        .HasColumnType("text")
                        .HasColumnName("fore_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Orcid")
                        .HasColumnType("text")
                        .HasColumnName("orcid");

                    b.Property<string>("Pmid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pmid");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.HasKey("Id");

                    b.HasIndex("LastName");

                    b.HasIndex("Orcid");

                    b.HasIndex("StudyNctId");

                    b.ToTable("study_authors", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyConditionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.HasKey("Id");

                    b.HasIndex("Condition");

                    b.HasIndex("StudyNctId");

                    b.ToTable("study_conditions", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyEntity", b =>
                {
                    b.Property<string>("NctId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nct_id");

                    b.Property<string>("Allocation")
                        .HasColumnType("text")
                        .HasColumnName("allocation");

                    b.Property<string>("BriefSummary")
                        .HasColumnType("text")
                        .HasColumnName("brief_summary");

                    b.Property<string>("BriefTitle")
                        .HasColumnType("text")
                        .HasColumnName("brief_title");

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("completion_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EnrollmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_count");

                    b.Property<string>("InterventionModel")
                        .HasColumnType("text")
                        .HasColumnName("intervention_model");

                    b.Property<bool>("IsIncomplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_incomplete");

                    b.Property<string>("MaximumAge")
                        .HasColumnType("text")
                        .HasColumnName("maximum_age");

                    b.Property<string>("MinimumAge")
                        .HasColumnType("text")
                        .HasColumnName("minimum_age");

                    b.Property<string>("OfficialTitle")
                        .HasColumnType("text")
                        .HasColumnName("official_title");

                    b.Property<string>("OverallStatus")
                        .HasColumnType("text")
                        .HasColumnName("overall_status");

                    b.Property<string>("PrimaryPurpose")
                        .HasColumnType("text")
                        .HasColumnName("primary_purpose");

                    b.Property<string>("Sex")
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateOnly?>("StudyFirstPostDate")
                        .HasColumnType("date")
                        .HasColumnName("study_first_post_date");

                    b.Property<string>("StudyType")
                        .HasColumnType("text")
                        .HasColumnName("study_type");

                    b.HasKey("NctId");

                    b.ToTable("studies", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyKeywordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.HasKey("Id");

                    b.HasIndex("Keyword");

                    b.HasIndex("StudyNctId");

                    b.ToTable("study_keywords", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyLocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Facility")
                        .HasColumnType("text")
                        .HasColumnName("facility");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("Country");

                    b.HasIndex("Facility");

                    b.HasIndex("State");

                    b.HasIndex("StudyNctId");

                    b.ToTable("study_locations", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyPhaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<string>("StudyNctId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_nct_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyNctId");

                    b.ToTable("study_phases", (string)null);
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.InvestigatorEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Investigators")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.PubmedStudyEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("PubmedStudies")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.ScrapeEventEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.PipelineRunEntity", "PipelineRun")
                        .WithMany()
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PipelineRun");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyAuthorEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Authors")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyConditionEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Conditions")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyKeywordEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Keywords")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyLocationEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Locations")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyPhaseEntity", b =>
                {
                    b.HasOne("Scrapers.Persistence.Entities.StudyEntity", "Study")
                        .WithMany("Phases")
                        .HasForeignKey("StudyNctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Scrapers.Persistence.Entities.StudyEntity", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Conditions");

                    b.Navigation("Investigators");

                    b.Navigation("Keywords");

                    b.Navigation("Locations");

                    b.Navigation("Phases");

                    b.Navigation("PubmedStudies");
                });
#pragma warning restore 612, 618
        }
    }
}
