[program:clinicaltrialdata-ingestion]
command=/opt/clinicaltrialdata/ingestion/IngestionApp
directory=/opt/clinicaltrialdata/ingestion
user=ct-deploy
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/clinicaltrialdata-ingestion.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/clinicaltrialdata-ingestion-err.log
stderr_logfile_maxbytes=100MB
stderr_logfile_backups=5
environment=ASPNETCORE_ENVIRONMENT=Production,POSTGRES_CONNECTION_STRING=%(ENV_POSTGRES_CONNECTION_STRING)s
