[program:clinicaltrialdata-frontend]
command=/opt/clinicaltrialdata/frontend/Frontend
directory=/opt/clinicaltrialdata/frontend
user=ct-deploy
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/clinicaltrialdata-frontend.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/clinicaltrialdata-frontend-err.log
stderr_logfile_maxbytes=100MB
stderr_logfile_backups=5
environment=ASPNETCORE_ENVIRONMENT=Production,ASPNETCORE_URLS=http://localhost:5001,POSTGRES_CONNECTION_STRING=%(ENV_POSTGRES_CONNECTION_STRING)s
